spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  web:
    resources:
      add-mappings: false

reset-database:
  api-key: ${RESET_DATABASE_API_KEY}

recaptcha:
  secret: ${RECAPTCHA_SECRET}
  verify-url: ${RECAPTCHA_VERIFY_URL}